// Public-Domain Text Source: Wuthering Heights (1847) by Emily Brontë

export const wutheringHeights = {
    1: [
        "I have just returned from a visit to my landlord—the solitary neighbour that I shall be troubled with.",
        "This is certainly a beautiful country!",
        "In all England, I do not believe that I could have fixed on a situation so completely removed from the stir of society.",
        "A perfect misanthropist’s heaven—and Mr. Heathcliff and I are such a suitable pair to divide the desolation between us.",
        "A capital fellow!",
        "He little imagined how my heart warmed towards him when I beheld his black eyes withdraw so suspiciously under their brows.",
        "As I rode up, I saw him lean on the gate to wait for me.",
        "He did not even conclude the ceremony of lifting his hat, but merely stared.",
        "I began to feel out of place at once.",
        "‘Thrushcross Grange is my own, sir,’ I said.",
        "A nod was the answer.",
        "I felt interested in a man who seemed more exaggeratedly reserved than myself.",
        "Wuthering Heights is the name of Mr. Heathcliff’s dwelling.",
        "‘Wuthering’ being a provincial adjective describing the atmospheric tumult to which its station is exposed in stormy weather.",
        "Pure, bracing ventilation they must have up there.",
        "One may guess the power of the north wind blowing over the edge by the occasional glance one has at the gaunt thorns.",
        "They stretch their limbs one way, as if craving alms of the sun.",
        "Fortunately, the architect had the foresight to build it strong.",
        "The narrow windows are deeply set in the wall.",
        "The corners defended with large jutting stones.",
        "Before passing the threshold, I paused to admire a quantity of grotesque carvings.",
        "Above the principal door, I detected the date ‘1500’ and the name ‘Hareton Earnshaw.’",
        "I knocked, and a hearty voice bade me enter.",
        "A huge, warm fireplace welcomed me, glowing with peat and flaming turf.",
        "My host pointed to a seat with a grim nod."
    ],
    2: [
        "Yesterday’s journey to Wuthering Heights had left me curious and somewhat uneasy.",
        "Determined to learn more of my landlord, I returned there the next morning.",
        "The day was cold and bleak, but I set out regardless.",
        "When I reached the house, I found a young woman who appeared to be mistress of the place.",
        "Her countenance was both handsome and fierce.",
        "I asked if Mr. Heathcliff was within.",
        "She replied curtly and led me to the sitting-room.",
        "Heathcliff greeted me with the same dark reserve as before.",
        "A strange young man lounged nearby, glowering at me with evident hostility.",
        "I attempted to introduce myself, but my efforts failed miserably.",
        "My mention of Thrushcross Grange seemed to irritate the trio.",
        "The woman’s manner alternated between disdain and suppressed emotion.",
        "The young man spoke little, but his eyes followed me with irritation.",
        "A pack of snarling dogs surrounded my chair, alarming me greatly.",
        "Their barking grew uncontrollable.",
        "One of the servants scolded them, but the noise continued.",
        "Suddenly, one of the dogs sprang at me.",
        "I staggered back, and in the confusion, I received a severe blow.",
        "The servants rushed to my aid.",
        "Heathcliff looked on with a cold expression.",
        "I felt humiliated by the entire scene.",
        "My hosts seemed indifferent to my discomfort.",
        "When the commotion finally subsided, I was shown to a seat again.",
        "With little ceremony, Heathcliff allowed me to depart.",
        "I returned to the Grange, resolved to avoid such visits in future."
    ],
    3: [
        "Upon reaching Thrushcross Grange, I found that the snow had grown deep.",
        "My servant, Zillah, showed me to a small chamber upstairs.",
        "The room was cold, and the wind rattled against the windowpanes.",
        "I looked around and noticed several old books scattered on a shelf.",
        "Opening one, I found the name ‘Catherine Earnshaw’ written repeatedly.",
        "Her handwriting varied from childish scrawl to mature script.",
        "The margins were filled with notes and diary-like entries.",
        "Curious, I read several passages.",
        "They described quarrels, lessons, punishments, and wild joy shared with a companion named Heathcliff.",
        "The entries suggested a turbulent childhood.",
        "As I read, the storm outside grew more violent.",
        "The candle flickered, and shadows danced against the walls.",
        "I began to feel uneasy, surrounded by relics of a past life.",
        "At last, exhausted, I drifted into an uneasy sleep.",
        "Suddenly, I felt a cold hand grasp my own.",
        "Terrified, I cried out.",
        "A voice outside my door demanded to know the cause of my shouting.",
        "Heathcliff appeared, wild with fear and anger.",
        "He believed I had disturbed Catherine’s spirit.",
        "He thrust open the window, calling her name into the night.",
        "His agony shocked me.",
        "He begged the unseen presence to return to him.",
        "The storm howled in reply.",
        "He finally dismissed me from the chamber.",
        "I departed trembling, unsure of what I had witnessed."
    ],
    4: [
        "The following morning, I questioned Mrs. Dean about the strange events at Wuthering Heights.",
        "She seemed reluctant at first but soon agreed to tell me the history of the household.",
        "She began with the arrival of Heathcliff, many years ago.",
        "Mr. Earnshaw had found the child wandering in the streets of Liverpool.",
        "He brought the boy home, to the dismay of his family.",
        "Catherine was delighted with the newcomer.",
        "Hindley, her brother, considered Heathcliff an interloper.",
        "Earnshaw loved the boy and favoured him openly.",
        "This partiality embittered Hindley.",
        "Catherine and Heathcliff became inseparable companions.",
        "Their mischievous adventures were notorious.",
        "Mrs. Dean recalled their wild spirits with a mixture of fondness and reproach.",
        "Hindley’s resentment deepened as the years passed.",
        "Earnshaw’s failing health worsened.",
        "On his deathbed, he prayed that his children would live in harmony.",
        "His wish was not fulfilled.",
        "Hindley inherited the estate and immediately degraded Heathcliff’s position.",
        "Catherine tried to comfort her friend.",
        "Heathcliff endured the humiliation in silence.",
        "The atmosphere at Wuthering Heights grew grim after Earnshaw’s death.",
        "Catherine remained lively, but her brother’s tyranny affected her.",
        "She and Heathcliff continued their rambles on the moors.",
        "Mrs. Dean sighed as she described their fierce loyalty.",
        "She declared that nothing could part those two at that time.",
        "I listened closely, eager to hear more of their story."
    ],
    5: [
        "Mrs. Dean resumed her tale the next evening.",
        "She described old Mr. Earnshaw’s final days in more detail.",
        "The old man had grown weak and irritable.",
        "Catherine tried to cheer him, but her lively spirits often vexed him.",
        "Heathcliff remained his favourite.",
        "Hindley took every opportunity to provoke quarrels.",
        "The household lived in constant tension.",
        "Mrs. Dean recalled many nights spent calming disputes.",
        "Earnshaw’s affection for the strange child never wavered.",
        "He worried continually about Heathcliff’s welfare.",
        "As sickness overtook him, his temper worsened.",
        "He fretted about Catherine’s behaviour and Hindley’s cruelty.",
        "One evening, Catherine hid behind his chair, hoping to surprise him.",
        "Her prank angered him sorely.",
        "He declared that she was a wicked, ungrateful girl.",
        "Catherine wept bitterly at the rebuke.",
        "The children’s quarrels exhausted the dying man.",
        "At last, he lay down for the final time.",
        "Heathcliff knelt beside him in silent grief.",
        "The old man blessed him with his last breath.",
        "The household mourned, but change soon swept through it.",
        "Hindley returned home with a wife.",
        "His marriage brought unexpected changes to the estate.",
        "He assumed absolute authority over the house.",
        "Mrs. Dean ended her account for the night, leaving much untold."
    ],
    6: [
        "Mrs. Dean continued her narrative by describing a reckless adventure undertaken by Catherine and Heathcliff.",
        "One summer evening, the pair strayed beyond their usual bounds on the moors.",
        "They wandered to the edge of Thrushcross Grange.",
        "Curiosity drove them to peer through the windows.",
        "Inside, they saw Edgar and Isabella Linton quarrelling over a lapdog.",
        "Heathcliff laughed at the display, calling the Lintons pampered weaklings.",
        "Catherine joined in his mirth.",
        "Their laughter attracted the notice of the household.",
        "The Lintons’ servants rushed out to seize the intruders.",
        "Heathcliff escaped, but Catherine stumbled and was caught.",
        "The watchdog sprang at her, tearing her ankle.",
        "The Linton family, shocked by the injury, carried her indoors.",
        "Heathcliff watched helplessly from the garden.",
        "He returned to Wuthering Heights alone, angry and distressed.",
        "Hindley, discovering Catherine’s absence, blamed Heathcliff for the escapade.",
        "Heathcliff endured his abuse in silence.",
        "Meanwhile, Catherine remained at the Grange for five weeks.",
        "Mrs. Dean explained that the Lintons wished to civilise her manners.",
        "They treated her as a young lady of great promise.",
        "Her wound healed slowly.",
        "The Lintons grew fond of her company.",
        "When Catherine finally returned home, she appeared altered.",
        "Heathcliff was astonished by her refined appearance.",
        "The changes in her manner wounded him deeply.",
        "That evening marked a turning point in their relationship."
    ],
    7: [
        "Catherine’s return to Wuthering Heights caused quite a stir among its inhabitants.",
        "Her elegant clothes and polished behaviour impressed everyone except Hindley.",
        "Heathcliff felt keenly the contrast between them.",
        "He retreated to the kitchen in humiliation.",
        "Mrs. Dean encouraged him to wash and comb his hair.",
        "Heathcliff resisted her advice.",
        "When Catherine came to see him, she laughed at his appearance.",
        "Her laughter wounded him, though she meant no harm.",
        "Edgar Linton soon arrived at the house to call on Catherine.",
        "Hindley welcomed him with unusual politeness.",
        "He treated Heathcliff with renewed contempt.",
        "Heathcliff, enraged, attempted to strike Edgar.",
        "Catherine scolded him for his behaviour.",
        "Hindley seized the moment to punish Heathcliff harshly.",
        "He forbade Heathcliff to speak to Catherine.",
        "The boy endured the injustice with a smouldering wrath.",
        "Mrs. Dean attempted to console him, but her words failed.",
        "Heathcliff vowed to take revenge on Hindley someday.",
        "Catherine felt torn between affection and irritation.",
        "Her time at Thrushcross Grange had begun to change her tastes.",
        "Edgar’s gentle manners appealed to her.",
        "Heathcliff’s fierce temper troubled her increasingly.",
        "Mrs. Dean observed these shifts with concern.",
        "The household grew more divided as winter advanced.",
        "The seeds of future conflict were already taking root."
    ],
    8: [
        "Two years passed, and the atmosphere at Wuthering Heights changed drastically.",
        "Hindley’s young wife gave birth to a son named Hareton.",
        "For a time, her presence softened her husband’s temper.",
        "However, her health declined rapidly.",
        "Her death plunged Hindley into despair.",
        "He surrendered himself to drink and reckless living.",
        "The household fell into disorder.",
        "Heathcliff grew stronger and more determined.",
        "Catherine divided her time between the Heights and Thrushcross Grange.",
        "Her friendship with Edgar deepened.",
        "Mrs. Dean noted that Catherine’s manners improved daily.",
        "Heathcliff, meanwhile, grew more brooding and silent.",
        "Hareton’s upbringing was neglected.",
        "Mrs. Dean tried her best to care for the child.",
        "Hindley’s tyranny worsened.",
        "He abused both servants and guests alike.",
        "Heathcliff bore his mistreatment with grim patience.",
        "Catherine alone could soothe his temper.",
        "One afternoon, Edgar visited Catherine and found her quarrelling with Heathcliff.",
        "Their argument escalated until Catherine struck Heathcliff in anger.",
        "He fled the room in fury.",
        "Edgar tried to comfort her, but she wept bitterly.",
        "Mrs. Dean warned Catherine that her temper endangered her happiness.",
        "Catherine dismissed the warning with impatience.",
        "The rift between the old childhood friends grew deeper each day."
    ],
    9: [
        "Stormy weather surrounded the Grange as Mrs. Dean resumed her story.",
        "Catherine confided to her that she had accepted Edgar Linton’s proposal.",
        "Her confession was filled with excitement and uncertainty.",
        "She insisted that she loved Edgar.",
        "Yet she admitted that her feelings for Heathcliff were of a different kind.",
        "She declared that he was more herself than she was.",
        "She believed they were made of the same spirit.",
        "Mrs. Dean listened uneasily.",
        "Catherine explained that marrying Heathcliff would degrade her social standing.",
        "She believed Edgar would help her to become a great lady.",
        "Unbeknownst to either of them, Heathcliff overheard part of the conversation.",
        "He slipped away before Catherine expressed her true affection for him.",
        "Catherine soon realised he was gone.",
        "She searched the house frantically.",
        "A fierce storm broke out during the night.",
        "Heathcliff did not return.",
        "Edgar arrived to find Catherine distraught and feverish.",
        "Mrs. Dean tended to her for several days.",
        "Hindley raged about the house, uncaring of Catherine’s plight.",
        "At last, Catherine regained her strength.",
        "Edgar showed her great patience and devotion.",
        "She accepted his care gratefully.",
        "Heathcliff’s disappearance left a wound that never fully healed.",
        "Mrs. Dean concluded that this night changed all their lives.",
        "The stage was set for sorrow and bitterness in the years ahead."
    ],
    10: [
        "Mrs. Dean explained that three years passed before Heathcliff returned to the district.",
        "Catherine, now married to Edgar, lived comfortably at the Grange.",
        "Their marriage was peaceful, though not without strain.",
        "Isabella Linton adored her brother and often visited.",
        "Edgar maintained a quiet, refined household.",
        "Catherine occasionally displayed her old wilfulness.",
        "One evening, Heathcliff arrived unexpectedly at the Grange.",
        "His appearance had changed strikingly.",
        "He carried himself with new confidence and dignity.",
        "Catherine greeted him with overwhelming joy.",
        "Edgar was astonished and uneasy at the reunion.",
        "Heathcliff’s manners had improved, yet a fierce fire lingered in his eyes.",
        "He spoke warmly to Catherine but coolly to Edgar.",
        "Isabella blushed under his gaze.",
        "Edgar invited Heathcliff to stay briefly.",
        "The visit unsettled the household.",
        "Catherine insisted that her old friend be treated kindly.",
        "Edgar objected inwardly but remained polite.",
        "Heathcliff announced he would lodge at Wuthering Heights.",
        "Hindley, ruined by gambling, welcomed him for selfish reasons.",
        "Heathcliff showed a troubling interest in the property’s finances.",
        "Catherine sensed danger but refused to acknowledge it.",
        "Edgar feared Heathcliff’s influence on his sister.",
        "Isabella’s infatuation grew rapidly.",
        "A new and perilous chapter in their lives had begun."
    ],
    11: [
        "Mrs. Dean resumed her narrative by explaining that Catherine’s behavior became increasingly erratic after Heathcliff’s return.",
        "She quarrelled frequently with Edgar.",
        "He objected strongly to her continuing intimacy with Heathcliff.",
        "Catherine insisted that Edgar’s jealousy was unreasonable.",
        "Their arguments grew sharper each day.",
        "One afternoon, Isabella confided in Catherine that she admired Heathcliff.",
        "Catherine reacted with unusual fury.",
        "She declared that Heathcliff was incapable of loving anyone.",
        "Isabella, wounded by her tone, fled the room.",
        "Shortly afterward, Edgar confronted Heathcliff in the parlor.",
        "The conversation escalated quickly into open hostility.",
        "Edgar ordered Heathcliff to leave the house.",
        "Catherine intervened angrily.",
        "She accused Edgar of cowardice.",
        "Edgar retreated to another room, refusing further quarrel.",
        "Catherine, feeling betrayed by both men, locked herself in her chamber.",
        "Mrs. Dean attempted to calm her, but Catherine would not listen.",
        "Isabella’s infatuation deepened despite Catherine’s warnings.",
        "Heathcliff encouraged the young woman’s interest for his own designs.",
        "Edgar grew pale and anxious as he observed the mounting tensions.",
        "Catherine refused to reconcile with him.",
        "Her moods fluctuated wildly.",
        "Mrs. Dean feared that Catherine’s health would suffer.",
        "The household existed in a state of simmering unrest.",
        "Dark events seemed certain to follow."
    ],
    12: [
        "Catherine’s agitation soon passed into a dangerous fever.",
        "Mrs. Dean found her pacing the room and muttering incoherently.",
        "She refused to eat or sleep.",
        "At times, she believed herself still a child at Wuthering Heights.",
        "She called out for Heathcliff and her old haunts on the moors.",
        "Edgar remained by her side, distressed but helpless.",
        "Her delirium terrified the household.",
        "She accused Edgar of wishing her dead.",
        "She alternated between tears and laughter.",
        "Mrs. Dean tried to persuade her to rest, but Catherine would not listen.",
        "In her fevered ramblings, she spoke of death as a release.",
        "Edgar begged her to have pity on him.",
        "Her condition worsened as the night progressed.",
        "At last, she collapsed in exhaustion.",
        "Meanwhile, Isabella vanished from the Grange.",
        "Mrs. Dean discovered a note stating that Isabella had fled with Heathcliff.",
        "Edgar was stunned by the betrayal.",
        "He forbade Heathcliff ever to enter the Grange again.",
        "He resolved to protect Catherine from further distress.",
        "Mrs. Dean tended to her night and day.",
        "The fever finally began to break.",
        "Catherine grew quiet and pale.",
        "Her strength dwindled alarmingly.",
        "The household lived in constant fear for her life.",
        "Edgar’s sorrow weighed heavily on all who saw him."
    ],
    13: [
        "Catherine’s illness progressed slowly over several weeks.",
        "Edgar devoted himself entirely to her care.",
        "He rarely left her side.",
        "Mrs. Dean observed shifts in Catherine’s character as she grew weaker.",
        "She seemed gentler and less impulsive.",
        "Her beauty had become ethereal.",
        "Visitors were forbidden, but Edgar’s sister Isabella wrote frequently.",
        "Her letters described her new life at Wuthering Heights.",
        "She confessed that Heathcliff treated her with cruel indifference.",
        "Hindley’s drunken violence terrorized the household.",
        "Isabella begged Mrs. Dean for advice.",
        "Mrs. Dean dared not answer truthfully, fearing Edgar’s anger.",
        "Catherine occasionally asked after Isabella.",
        "Her strength was too diminished to dwell on troubling matters.",
        "Edgar maintained a calm façade, though grief consumed him.",
        "Spring arrived slowly.",
        "The sunshine revived Catherine somewhat.",
        "She spent hours gazing from her window.",
        "She longed to walk on the moors again.",
        "Edgar planned to take her outside when she grew stronger.",
        "Mrs. Dean dared to hope for her recovery.",
        "Catherine’s mind wandered between past and present.",
        "She spoke often of her childhood with Heathcliff.",
        "Edgar listened silently, unable to repress his pain.",
        "The fragile peace of the household hovered between despair and hope."
    ],
    14: [
        "Mrs. Dean finally obtained Edgar’s permission to visit Isabella at Wuthering Heights.",
        "She found the young woman pale and uneasy.",
        "Isabella confessed that her marriage had become a torment.",
        "Heathcliff treated her coldly and cruelly.",
        "Hindley’s presence made the house even more perilous.",
        "The servants obeyed Heathcliff out of fear rather than respect.",
        "Isabella regretted her impulsive elopement.",
        "Yet she refused to return to the Grange while Edgar’s anger remained fierce.",
        "Heathcliff questioned Mrs. Dean about Catherine’s health.",
        "He demanded to know why Edgar forbade him from visiting her.",
        "Mrs. Dean warned him that Catherine was too frail for agitation.",
        "Heathcliff dismissed her concerns.",
        "He insisted that Catherine belonged to him in spirit.",
        "Isabella listened with growing distress.",
        "Mrs. Dean begged Heathcliff to consider Catherine’s condition.",
        "He accused Edgar of destroying her happiness.",
        "His rage seemed uncontrollable.",
        "Isabella trembled at his violent passions.",
        "Mrs. Dean delivered Edgar’s message forbidding Heathcliff from the Grange.",
        "Heathcliff swore that no force could keep him from Catherine if she wished to see him.",
        "Mrs. Dean fled the house in fear.",
        "She returned to the Grange exhausted.",
        "Edgar listened intently to her account.",
        "He refused to speak Heathcliff’s name again.",
        "The storm that hung over their lives deepened further."
    ],
    15: [
        "Catherine’s strength waned again as spring advanced.",
        "Her face grew thin and translucent.",
        "Edgar watched her with desperate tenderness.",
        "He scarcely ate or slept.",
        "Mrs. Dean remained constantly in attendance.",
        "One evening, Heathcliff appeared at the Grange despite Edgar’s orders.",
        "He demanded to see Catherine.",
        "Mrs. Dean hesitated but allowed him into her chamber.",
        "Catherine revived at the sight of him.",
        "She clung to him with fierce emotion.",
        "They reproached one another bitterly and lovingly at once.",
        "Heathcliff accused her of breaking his heart.",
        "She insisted that he had wronged her by leaving.",
        "Their anguish shook the room.",
        "Mrs. Dean warned them to calm themselves for Catherine’s sake.",
        "Edgar entered unexpectedly.",
        "He stood in silent shock at the scene.",
        "Heathcliff prepared to defend himself.",
        "Catherine fainted before any confrontation could occur.",
        "Edgar rushed to her side.",
        "Heathcliff retreated slowly from the chamber.",
        "He left the house with a face carved in agony.",
        "Mrs. Dean feared Catherine could not survive the night.",
        "Edgar sent for the doctor immediately.",
        "The tragedy that followed was inevitable."
    ],
};
